config/routes.rb
Rails.application.routes.draw do
  get 'explore/:api' => 'api#explore', :as => :explore_api

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  } do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  root to: 'home#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :timeoutable

  devise :omniauthable, omniauth_providers: %i[doorkeeper]

  def self.from_omniauth(auth)
    where(provider: auth.provider, email: auth.info.email).first_or_create do |user|
      user.email = auth.info.email
      user.uid = auth.uid
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
    end
  end

  def update_doorkeeper_credentials(auth)
    update(
      doorkeeper_access_token: auth.credentials.token,
      doorkeeper_refresh_token: auth.credentials.refresh_token
    )
  end

  def timeout_in
    1.minute
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  respond_to :json

  def explore
    @json = doorkeeper_access_token.get("api/v1/#{params[:api]}").parsed
    respond_with @json
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def doorkeeper_oauth_client
    @doorkeeper_oauth_client ||= OAuth2::Client.new(
      ENV.fetch("DOORKEEPER_APP_ID"),
      ENV.fetch("DOORKEEPER_APP_SECRET"),
      site: ENV.fetch("DOORKEEPER_APP_URL")
    )
  end

  def doorkeeper_access_token
    @doorkeeper_access_token ||=
      if current_user
        OAuth2::AccessToken.new(
          doorkeeper_oauth_client, current_user.doorkeeper_access_token
        )
      end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    doorkeeper_oauth_client
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def doorkeeper
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      @user.update_doorkeeper_credentials(request.env["omniauth.auth"])
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Doorkeeper") if is_navigational_format?
    else
      session["devise.doorkeeper_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<% unless signed_in? %>
  <h2>Sign in first to explore the provider's API</h2>

  <p>
    <%= link_to "Sign in with OAuth 2 provider", @doorkeeper_oauth_client.auth_code.authorize_url(redirect_uri: ENV['DOORKEEPER_APP_REDIRECT_CALLBACK']), class: "btn btn-primary" %>
  </p>
<% else %>
  <h2>Explore the api</h2>

  <p>
    <%= link_to "My Credentials", explore_api_path(:me, format: :json), class: "btn btn-primary data-explore" %>
    <%= link_to "Projects", explore_api_path(:projects, format: :json), class: "btn btn-secondary data-explore" %>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
  </p>

  <p>You are logged in as <%= current_user.email %></p>

  <p><pre id="display-json">Select one of the api methods above</pre></p>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <title>Doorkeeper Devise + Omniauth Integration</title>
  </head>

  <body>
    <div class="container-fluid">
      <div class="container py-md-3">
        <div class="row">
          <div class="col">
            <% if notice %><div class="alert alert-success" role="alert"><%= notice %></div><% end %>
            <% if alert %><div class="alert alert-warning" role="alert"><%= alert %></div><% end %>

            <%= yield %>
          </div>
        </div>
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>